import dotenv from 'dotenv';
import connectDB from '../config/db';
import User from '../models/User';
import Product from '../models/Product';
import Category from '../models/Category';

dotenv.config();

const categories = [
  {
    name: 'Mountain Bikes',
    slug: 'mountain-bikes',
    description: 'Conquer any terrain with our rugged mountain bikes',
    image: 'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=500',
  },
  {
    name: 'Road Bikes',
    slug: 'road-bikes',
    description: 'Speed and performance for the open road',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
  },
  {
    name: 'Electric Bikes',
    slug: 'electric-bikes',
    description: 'Powered rides for effortless cycling',
    image: 'https://images.unsplash.com/photo-1591081804394-e30d2e2417fb?w=500',
  },
  {
    name: 'BMX Bikes',
    slug: 'bmx-bikes',
    description: 'Tricks, stunts, and freestyle riding',
    image: 'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=500',
  },
  {
    name: 'Hybrid Bikes',
    slug: 'hybrid-bikes',
    description: 'Versatile bikes for city and trail',
    image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=500',
  },
  {
    name: 'Kids Bikes',
    slug: 'kids-bikes',
    description: 'Safe and fun bikes for young riders',
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=500',
  },
  {
    name: 'Gravel Bikes',
    slug: 'gravel-bikes',
    description: 'Adventure-ready for mixed terrain',
    image: 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=500',
  },
  {
    name: 'Cruiser Bikes',
    slug: 'cruiser-bikes',
    description: 'Comfortable rides for leisurely cycling',
    image: 'https://images.unsplash.com/photo-1559589689-577aabd1db4f?w=500',
  },
];

const seedDB = async () => {
  try {
    await connectDB();

    // Clear existing data
    await User.deleteMany({});
    await Category.deleteMany({});
    await Product.deleteMany({});

    console.log('Cleared existing data');

    // Create admin user
    const admin = await User.create({
      name: 'Admin User',
      email: 'admin@bikehub.com',
      password: 'SecureAdmin2024!',
      role: 'admin',
    });

    console.log('Admin user created');

    // Create categories
    const createdCategories = await Category.insertMany(categories);
    console.log('Categories created');

    // Create products (50+ bikes across all categories)
    const products = [
      // MOUNTAIN BIKES (Category 0) - 10 bikes
      {
        name: 'Trek Marlin 7',
        slug: 'trek-marlin-7',
        description: 'Hardtail mountain bike with RockShox fork, 29" wheels, 2x9 Shimano drivetrain. Perfect for trail riding and cross-country adventures.',
        price: 1099.99,
        compareAtPrice: 1249.99,
        category: createdCategories[0]._id,
        images: [
          'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=800',
          'https://images.unsplash.com/photo-1511994714008-b6c582f1b1b8?w=800',
        ],
        stock: 15,
        tags: ['mountain', 'trek', 'hardtail', 'featured'],
        featured: true,
        rating: 4.7,
        numReviews: 89,
      },
      {
        name: 'Specialized Stumpjumper Comp',
        slug: 'specialized-stumpjumper-comp',
        description: 'Full suspension trail bike with 140mm travel, carbon frame, and FOX suspension. Built for aggressive trail riding.',
        price: 3899.99,
        compareAtPrice: 4299.99,
        category: createdCategories[0]._id,
        images: ['https://images.unsplash.com/photo-1617050318658-a9a3175e34cb?w=800'],
        stock: 8,
        tags: ['mountain', 'specialized', 'full-suspension', 'featured'],
        featured: true,
        rating: 4.9,
        numReviews: 156,
      },
      {
        name: 'Giant Talon 1',
        slug: 'giant-talon-1',
        description: 'Entry-level hardtail with SR Suntour fork, 27.5" wheels, Shimano 1x9 gearing. Great for beginners.',
        price: 729.99,
        category: createdCategories[0]._id,
        images: ['https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=800'],
        stock: 20,
        tags: ['mountain', 'giant', 'hardtail', 'beginner'],
        featured: false,
        rating: 4.5,
        numReviews: 67,
      },
      {
        name: 'Cannondale Habit Carbon 2',
        slug: 'cannondale-habit-carbon-2',
        description: 'Versatile trail bike with 130/120mm travel, carbon frame, 29" wheels, and RockShox suspension.',
        price: 4299.99,
        category: createdCategories[0]._id,
        images: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800'],
        stock: 6,
        tags: ['mountain', 'cannondale', 'full-suspension', 'carbon'],
        featured: false,
        rating: 4.8,
        numReviews: 94,
      },
      {
        name: 'Santa Cruz Chameleon',
        slug: 'santa-cruz-chameleon',
        description: 'Aggressive hardtail with 27.5+ capability, aluminum frame, and dropper post. Trail or park ready.',
        price: 2299.99,
        compareAtPrice: 2499.99,
        category: createdCategories[0]._id,
        images: ['https://images.unsplash.com/photo-1511994714008-b6c582f1b1b8?w=800'],
        stock: 12,
        tags: ['mountain', 'santa-cruz', 'hardtail', 'featured'],
        featured: true,
        rating: 4.7,
        numReviews: 78,
      },
      {
        name: 'Scott Spark 960',
        slug: 'scott-spark-960',
        description: 'Cross-country race bike with 120mm TwinLoc suspension, carbon frame, and SRAM NX Eagle drivetrain.',
        price: 3599.99,
        category: createdCategories[0]._id,
        images: ['https://images.unsplash.com/photo-1617050318658-a9a3175e34cb?w=800'],
        stock: 9,
        tags: ['mountain', 'scott', 'xc', 'carbon'],
        featured: false,
        rating: 4.8,
        numReviews: 112,
      },
      {
        name: 'Yeti SB130',
        slug: 'yeti-sb130',
        description: 'Premium trail bike with 130mm Switch Infinity suspension, carbon frame, and top-tier components.',
        price: 6999.99,
        category: createdCategories[0]._id,
        images: ['https://images.unsplash.com/photo-1511994714008-b6c582f1b1b8?w=800'],
        stock: 4,
        tags: ['mountain', 'yeti', 'premium', 'carbon'],
        featured: false,
        rating: 5.0,
        numReviews: 45,
      },
      {
        name: 'Pivot Trail 429',
        slug: 'pivot-trail-429',
        description: 'Versatile 29er with 120/115mm travel, DW-Link suspension, and lightweight carbon construction.',
        price: 5499.99,
        category: createdCategories[0]._id,
        images: ['https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=800'],
        stock: 7,
        tags: ['mountain', 'pivot', 'carbon', '29er'],
        featured: false,
        rating: 4.9,
        numReviews: 63,
      },
      {
        name: 'Kona Process 134',
        slug: 'kona-process-134',
        description: 'All-mountain bike with 150/134mm travel, aluminum frame, and aggressive geometry for downhill performance.',
        price: 2899.99,
        category: createdCategories[0]._id,
        images: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800'],
        stock: 11,
        tags: ['mountain', 'kona', 'all-mountain', 'enduro'],
        featured: false,
        rating: 4.6,
        numReviews: 72,
      },
      {
        name: 'Rocky Mountain Altitude',
        slug: 'rocky-mountain-altitude',
        description: 'Enduro bike with 165/148mm travel, carbon frame, and adjustable geometry for any terrain.',
        price: 6299.99,
        category: createdCategories[0]._id,
        images: ['https://images.unsplash.com/photo-1617050318658-a9a3175e34cb?w=800'],
        stock: 5,
        tags: ['mountain', 'rocky-mountain', 'enduro', 'carbon'],
        featured: false,
        rating: 4.8,
        numReviews: 88,
      },

      // ROAD BIKES (Category 1) - 10 bikes
      {
        name: 'Trek Domane SL 5',
        slug: 'trek-domane-sl-5',
        description: 'Endurance road bike with IsoSpeed decoupler, carbon frame, disc brakes, and Shimano 105 groupset.',
        price: 3499.99,
        compareAtPrice: 3799.99,
        category: createdCategories[1]._id,
        images: [
          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
          'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800',
        ],
        stock: 12,
        tags: ['road', 'trek', 'endurance', 'featured'],
        featured: true,
        rating: 4.8,
        numReviews: 134,
      },
      {
        name: 'Specialized Tarmac SL7',
        slug: 'specialized-tarmac-sl7',
        description: 'Race-focused road bike with Rider-First Engineered frame, full carbon, Shimano Ultegra Di2 electronic shifting.',
        price: 5999.99,
        category: createdCategories[1]._id,
        images: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800'],
        stock: 7,
        tags: ['road', 'specialized', 'race', 'carbon', 'featured'],
        featured: true,
        rating: 4.9,
        numReviews: 178,
      },
      {
        name: 'Cannondale CAAD13',
        slug: 'cannondale-caad13',
        description: 'Lightweight aluminum race bike with disc brakes, Shimano 105, and SmartForm C1 alloy frame.',
        price: 2299.99,
        category: createdCategories[1]._id,
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
        stock: 15,
        tags: ['road', 'cannondale', 'aluminum', 'race'],
        featured: false,
        rating: 4.7,
        numReviews: 92,
      },
      {
        name: 'Giant TCR Advanced Pro 1',
        slug: 'giant-tcr-advanced-pro-1',
        description: 'Aero road bike with Advanced-Grade Composite frame, integrated cockpit, and Shimano Ultegra.',
        price: 4699.99,
        category: createdCategories[1]._id,
        images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800'],
        stock: 9,
        tags: ['road', 'giant', 'aero', 'carbon'],
        featured: false,
        rating: 4.8,
        numReviews: 106,
      },
      {
        name: 'Scott Addict RC 20',
        slug: 'scott-addict-rc-20',
        description: 'Climbing specialist with HMF carbon frame, Shimano Ultegra, and exceptional stiffness-to-weight ratio.',
        price: 5499.99,
        category: createdCategories[1]._id,
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
        stock: 6,
        tags: ['road', 'scott', 'climbing', 'carbon'],
        featured: false,
        rating: 4.9,
        numReviews: 84,
      },
      {
        name: 'Cervélo Caledonia 5',
        slug: 'cervelo-caledonia-5',
        description: 'Endurance bike with aero touches, carbon frame, tire clearance up to 35mm, and Shimano 105.',
        price: 3899.99,
        category: createdCategories[1]._id,
        images: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800'],
        stock: 10,
        tags: ['road', 'cervelo', 'endurance', 'carbon'],
        featured: false,
        rating: 4.7,
        numReviews: 71,
      },
      {
        name: 'Pinarello Dogma F',
        slug: 'pinarello-dogma-f',
        description: 'Pro-level race bike with Torayca T1100 1K carbon, asymmetric frame design, and Dura-Ace Di2.',
        price: 12999.99,
        category: createdCategories[1]._id,
        images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800'],
        stock: 3,
        tags: ['road', 'pinarello', 'premium', 'pro'],
        featured: false,
        rating: 5.0,
        numReviews: 42,
      },
      {
        name: 'Bianchi Oltre RC',
        slug: 'bianchi-oltre-rc',
        description: 'Italian racing heritage with CounterVail carbon, Shimano Ultegra Di2, and legendary Celeste color.',
        price: 6799.99,
        category: createdCategories[1]._id,
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
        stock: 5,
        tags: ['road', 'bianchi', 'italian', 'carbon'],
        featured: false,
        rating: 4.8,
        numReviews: 66,
      },
      {
        name: 'Colnago V4Rs',
        slug: 'colnago-v4rs',
        description: 'Cutting-edge aero road bike with CC.01 carbon monocoque, T47 bottom bracket, and premium build.',
        price: 11499.99,
        category: createdCategories[1]._id,
        images: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800'],
        stock: 4,
        tags: ['road', 'colnago', 'aero', 'premium'],
        featured: false,
        rating: 4.9,
        numReviews: 38,
      },
      {
        name: 'BMC Roadmachine 02',
        slug: 'bmc-roadmachine-02',
        description: 'Swiss engineering with Tuned Compliance Concept, carbon frame, SRAM Rival eTap AXS wireless shifting.',
        price: 5299.99,
        category: createdCategories[1]._id,
        images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800'],
        stock: 8,
        tags: ['road', 'bmc', 'endurance', 'wireless'],
        featured: false,
        rating: 4.7,
        numReviews: 79,
      },

      // ELECTRIC BIKES (Category 2) - 8 bikes
      {
        name: 'Trek Powerfly 5',
        slug: 'trek-powerfly-5',
        description: 'E-MTB with Bosch Performance CX motor, 625Wh battery, and RockShox suspension. Range up to 60 miles.',
        price: 3799.99,
        compareAtPrice: 4199.99,
        category: createdCategories[2]._id,
        images: [
          'https://images.unsplash.com/photo-1591081804394-e30d2e2417fb?w=800',
          'https://images.unsplash.com/photo-1558981852-426c6c22a060?w=800',
        ],
        stock: 10,
        tags: ['ebike', 'trek', 'mountain', 'featured'],
        featured: true,
        rating: 4.8,
        numReviews: 143,
      },
      {
        name: 'Specialized Turbo Vado 4.0',
        slug: 'specialized-turbo-vado-4',
        description: 'Premium commuter e-bike with 500Wh battery, hydraulic disc brakes, and integrated lights. 80-mile range.',
        price: 3999.99,
        category: createdCategories[2]._id,
        images: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800'],
        stock: 12,
        tags: ['ebike', 'specialized', 'commuter', 'featured'],
        featured: true,
        rating: 4.9,
        numReviews: 167,
      },
      {
        name: 'Giant Explore E+ 2',
        slug: 'giant-explore-e-plus-2',
        description: 'Hybrid e-bike with SyncDrive Sport motor, 500Wh battery, and comfortable upright position.',
        price: 2799.99,
        category: createdCategories[2]._id,
        images: ['https://images.unsplash.com/photo-1591081804394-e30d2e2417fb?w=800'],
        stock: 15,
        tags: ['ebike', 'giant', 'hybrid', 'commuter'],
        featured: false,
        rating: 4.6,
        numReviews: 98,
      },
      {
        name: 'Cannondale Moterra Neo 3',
        slug: 'cannondale-moterra-neo-3',
        description: 'Full suspension e-MTB with Bosch Smart System, 750Wh battery, and 150/140mm travel.',
        price: 4999.99,
        category: createdCategories[2]._id,
        images: ['https://images.unsplash.com/photo-1558981852-426c6c22a060?w=800'],
        stock: 7,
        tags: ['ebike', 'cannondale', 'mountain', 'full-suspension'],
        featured: false,
        rating: 4.8,
        numReviews: 76,
      },
      {
        name: 'Rad Power RadRover 6 Plus',
        slug: 'rad-power-radrover-6-plus',
        description: 'Fat tire e-bike with 750W motor, 672Wh battery, and puncture-resistant tires. All-terrain capability.',
        price: 1999.99,
        compareAtPrice: 2299.99,
        category: createdCategories[2]._id,
        images: ['https://images.unsplash.com/photo-1591081804394-e30d2e2417fb?w=800'],
        stock: 18,
        tags: ['ebike', 'rad-power', 'fat-tire', 'value'],
        featured: false,
        rating: 4.5,
        numReviews: 234,
      },
      {
        name: 'Riese & Müller Supercharger2 GT',
        slug: 'riese-muller-supercharger2-gt',
        description: 'Premium touring e-bike with dual batteries (1125Wh), Bosch motor, and full suspension.',
        price: 7499.99,
        category: createdCategories[2]._id,
        images: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800'],
        stock: 5,
        tags: ['ebike', 'riese-muller', 'touring', 'premium'],
        featured: false,
        rating: 5.0,
        numReviews: 54,
      },
      {
        name: 'VanMoof S5',
        slug: 'vanmoof-s5',
        description: 'Smart city e-bike with integrated technology, automatic gear shifting, and theft protection.',
        price: 3498.99,
        category: createdCategories[2]._id,
        images: ['https://images.unsplash.com/photo-1591081804394-e30d2e2417fb?w=800'],
        stock: 9,
        tags: ['ebike', 'vanmoof', 'city', 'smart'],
        featured: false,
        rating: 4.6,
        numReviews: 112,
      },
      {
        name: 'Aventon Level.2',
        slug: 'aventon-level-2',
        description: 'Commuter e-bike with 500W motor, 672Wh battery, and torque sensor for natural pedal assist.',
        price: 1799.99,
        category: createdCategories[2]._id,
        images: ['https://images.unsplash.com/photo-1558981852-426c6c22a060?w=800'],
        stock: 14,
        tags: ['ebike', 'aventon', 'commuter', 'value'],
        featured: false,
        rating: 4.7,
        numReviews: 189,
      },

      // BMX BIKES (Category 3) - 6 bikes
      {
        name: 'Mongoose Legion L40',
        slug: 'mongoose-legion-l40',
        description: '20" freestyle BMX with Hi-Ten steel frame, 4-piece bars, and sealed bearings. Perfect for street and park.',
        price: 329.99,
        compareAtPrice: 379.99,
        category: createdCategories[3]._id,
        images: [
          'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=800',
          'https://images.unsplash.com/photo-1505705694340-019e1e335916?w=800',
        ],
        stock: 25,
        tags: ['bmx', 'mongoose', 'freestyle', 'featured'],
        featured: true,
        rating: 4.6,
        numReviews: 156,
      },
      {
        name: 'Sunday Soundwave Special',
        slug: 'sunday-soundwave-special',
        description: 'Pro-level BMX with full chromoly frame, Wave Dropouts, and Sunday componentry throughout.',
        price: 699.99,
        category: createdCategories[3]._id,
        images: ['https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=800'],
        stock: 12,
        tags: ['bmx', 'sunday', 'pro', 'chromoly'],
        featured: false,
        rating: 4.9,
        numReviews: 87,
      },
      {
        name: 'Kink Gap XL',
        slug: 'kink-gap-xl',
        description: '20.5" street BMX with heat-treated frame, aftermarket parts, and durable construction.',
        price: 549.99,
        category: createdCategories[3]._id,
        images: ['https://images.unsplash.com/photo-1505705694340-019e1e335916?w=800'],
        stock: 15,
        tags: ['bmx', 'kink', 'street', 'park'],
        featured: false,
        rating: 4.7,
        numReviews: 93,
      },
      {
        name: 'Fit Bike Co. PRK',
        slug: 'fit-bike-co-prk',
        description: 'Park-focused BMX with 100% chromoly frame and fork, sealed hubs, and grippy tires.',
        price: 599.99,
        category: createdCategories[3]._id,
        images: ['https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=800'],
        stock: 18,
        tags: ['bmx', 'fit', 'park', 'chromoly'],
        featured: false,
        rating: 4.8,
        numReviews: 71,
      },
      {
        name: 'Cult Gateway',
        slug: 'cult-gateway',
        description: 'Entry-level BMX with investment-cast dropouts, sealed mid BB, and quality components.',
        price: 399.99,
        category: createdCategories[3]._id,
        images: ['https://images.unsplash.com/photo-1505705694340-019e1e335916?w=800'],
        stock: 22,
        tags: ['bmx', 'cult', 'beginner', 'value'],
        featured: false,
        rating: 4.5,
        numReviews: 134,
      },
      {
        name: 'Haro Downtown DLX',
        slug: 'haro-downtown-dlx',
        description: '26" BMX cruiser with chromoly frame, 3-piece cranks, and comfortable geometry for all-day riding.',
        price: 649.99,
        category: createdCategories[3]._id,
        images: ['https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=800'],
        stock: 10,
        tags: ['bmx', 'haro', 'cruiser', '26-inch'],
        featured: false,
        rating: 4.7,
        numReviews: 64,
      },

      // HYBRID BIKES (Category 4) - 7 bikes
      {
        name: 'Trek FX 3 Disc',
        slug: 'trek-fx-3-disc',
        description: 'Versatile hybrid with Alpha Gold aluminum, disc brakes, and rack/fender mounts. Perfect commuter.',
        price: 899.99,
        compareAtPrice: 999.99,
        category: createdCategories[4]._id,
        images: [
          'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800',
          'https://images.unsplash.com/photo-1474496517593-015d8b59450d?w=800',
        ],
        stock: 20,
        tags: ['hybrid', 'trek', 'commuter', 'featured'],
        featured: true,
        rating: 4.7,
        numReviews: 198,
      },
      {
        name: 'Specialized Sirrus 3.0',
        slug: 'specialized-sirrus-3',
        description: 'Fitness hybrid with lightweight aluminum frame, Future Shock, and hydraulic disc brakes.',
        price: 1099.99,
        category: createdCategories[4]._id,
        images: ['https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800'],
        stock: 16,
        tags: ['hybrid', 'specialized', 'fitness', 'disc-brakes'],
        featured: false,
        rating: 4.8,
        numReviews: 142,
      },
      {
        name: 'Giant Escape 3',
        slug: 'giant-escape-3',
        description: 'Affordable hybrid with ALUXX aluminum frame, 7-speed drivetrain, and comfortable geometry.',
        price: 599.99,
        category: createdCategories[4]._id,
        images: ['https://images.unsplash.com/photo-1474496517593-015d8b59450d?w=800'],
        stock: 28,
        tags: ['hybrid', 'giant', 'value', 'beginner'],
        featured: false,
        rating: 4.5,
        numReviews: 267,
      },
      {
        name: 'Cannondale Quick CX 3',
        slug: 'cannondale-quick-cx-3',
        description: 'Fitness hybrid with SmartForm C3 alloy, suspension fork, and versatile tire clearance.',
        price: 849.99,
        category: createdCategories[4]._id,
        images: ['https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800'],
        stock: 14,
        tags: ['hybrid', 'cannondale', 'fitness', 'suspension'],
        featured: false,
        rating: 4.6,
        numReviews: 89,
      },
      {
        name: 'Marin Fairfax 2',
        slug: 'marin-fairfax-2',
        description: 'Urban commuter with Series 2 6061 aluminum, disc brakes, and integrated rack mounts.',
        price: 729.99,
        category: createdCategories[4]._id,
        images: ['https://images.unsplash.com/photo-1474496517593-015d8b59450d?w=800'],
        stock: 18,
        tags: ['hybrid', 'marin', 'commuter', 'urban'],
        featured: false,
        rating: 4.6,
        numReviews: 76,
      },
      {
        name: 'Bianchi C-Sport 2',
        slug: 'bianchi-c-sport-2',
        description: 'Italian hybrid with hydroformed aluminum, carbon fork, and Shimano Altus components.',
        price: 999.99,
        category: createdCategories[4]._id,
        images: ['https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800'],
        stock: 11,
        tags: ['hybrid', 'bianchi', 'carbon-fork', 'italian'],
        featured: false,
        rating: 4.7,
        numReviews: 62,
      },
      {
        name: 'Schwinn Vantage RX1',
        slug: 'schwinn-vantage-rx1',
        description: 'Drop bar hybrid with aluminum frame, 21-speed Shimano, and versatile road/path capability.',
        price: 649.99,
        category: createdCategories[4]._id,
        images: ['https://images.unsplash.com/photo-1474496517593-015d8b59450d?w=800'],
        stock: 19,
        tags: ['hybrid', 'schwinn', 'drop-bar', 'value'],
        featured: false,
        rating: 4.4,
        numReviews: 118,
      },

      // KIDS BIKES (Category 5) - 6 bikes
      {
        name: 'Specialized Jett 20',
        slug: 'specialized-jett-20',
        description: '20" kids bike with lightweight aluminum, single-speed, coaster brake, and included training wheels.',
        price: 299.99,
        compareAtPrice: 349.99,
        category: createdCategories[5]._id,
        images: [
          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800',
          'https://images.unsplash.com/photo-1566015534097-89a2c2d7e1f3?w=800',
        ],
        stock: 30,
        tags: ['kids', 'specialized', '20-inch', 'featured'],
        featured: true,
        rating: 4.8,
        numReviews: 212,
      },
      {
        name: 'Trek Precaliber 16',
        slug: 'trek-precaliber-16',
        description: '16" kids bike with low standover, wide range of fit, and easy-to-use coaster brake.',
        price: 249.99,
        category: createdCategories[5]._id,
        images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800'],
        stock: 35,
        tags: ['kids', 'trek', '16-inch', 'beginner'],
        featured: false,
        rating: 4.7,
        numReviews: 189,
      },
      {
        name: 'Giant XtC Jr 24',
        slug: 'giant-xtc-jr-24',
        description: '24" mountain bike for kids with ALUXX-Grade aluminum, suspension fork, and 7-speed gearing.',
        price: 449.99,
        category: createdCategories[5]._id,
        images: ['https://images.unsplash.com/photo-1566015534097-89a2c2d7e1f3?w=800'],
        stock: 22,
        tags: ['kids', 'giant', 'mountain', '24-inch'],
        featured: false,
        rating: 4.6,
        numReviews: 97,
      },
      {
        name: 'Cannondale Trail 20',
        slug: 'cannondale-trail-20',
        description: '20" kids mountain bike with lightweight frame, hand brakes, and grippy tires.',
        price: 379.99,
        category: createdCategories[5]._id,
        images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800'],
        stock: 26,
        tags: ['kids', 'cannondale', 'mountain', '20-inch'],
        featured: false,
        rating: 4.7,
        numReviews: 134,
      },
      {
        name: 'Schwinn Koen 20',
        slug: 'schwinn-koen-20',
        description: '20" cruiser-style kids bike with coaster brake, front hand brake, and fun colors.',
        price: 199.99,
        category: createdCategories[5]._id,
        images: ['https://images.unsplash.com/photo-1566015534097-89a2c2d7e1f3?w=800'],
        stock: 32,
        tags: ['kids', 'schwinn', 'cruiser', 'value'],
        featured: false,
        rating: 4.5,
        numReviews: 156,
      },
      {
        name: 'Woom 4',
        slug: 'woom-4',
        description: '20" premium kids bike with upright ergonomics, 8-speed, and lightweight aluminum (11.6 lbs).',
        price: 549.99,
        category: createdCategories[5]._id,
        images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800'],
        stock: 18,
        tags: ['kids', 'woom', 'premium', 'lightweight'],
        featured: false,
        rating: 5.0,
        numReviews: 84,
      },

      // GRAVEL BIKES (Category 6) - 6 bikes
      {
        name: 'Specialized Diverge Comp',
        slug: 'specialized-diverge-comp',
        description: 'Gravel bike with Future Shock 2.0, carbon frame, SRAM Rival, and clearance for 47mm tires.',
        price: 4299.99,
        compareAtPrice: 4699.99,
        category: createdCategories[6]._id,
        images: [
          'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800',
          'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800',
        ],
        stock: 9,
        tags: ['gravel', 'specialized', 'carbon', 'featured'],
        featured: true,
        rating: 4.9,
        numReviews: 128,
      },
      {
        name: 'Trek Checkpoint ALR 5',
        slug: 'trek-checkpoint-alr-5',
        description: 'Aluminum gravel bike with IsoSpeed, GRX 600 drivetrain, and mounts for bikepacking.',
        price: 2299.99,
        category: createdCategories[6]._id,
        images: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800'],
        stock: 14,
        tags: ['gravel', 'trek', 'aluminum', 'bikepacking'],
        featured: false,
        rating: 4.7,
        numReviews: 103,
      },
      {
        name: 'Canyon Grail CF SL 8',
        slug: 'canyon-grail-cf-sl-8',
        description: 'Carbon gravel bike with Hover Bar, SRAM Force eTap AXS, and compliance-focused geometry.',
        price: 3799.99,
        category: createdCategories[6]._id,
        images: ['https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800'],
        stock: 7,
        tags: ['gravel', 'canyon', 'carbon', 'wireless'],
        featured: false,
        rating: 4.8,
        numReviews: 76,
      },
      {
        name: 'Giant Revolt Advanced 2',
        slug: 'giant-revolt-advanced-2',
        description: 'Composite gravel bike with D-Fuse seatpost, Shimano GRX 800, and adventure-ready build.',
        price: 2899.99,
        category: createdCategories[6]._id,
        images: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800'],
        stock: 11,
        tags: ['gravel', 'giant', 'carbon', 'adventure'],
        featured: false,
        rating: 4.7,
        numReviews: 88,
      },
      {
        name: 'Santa Cruz Stigmata CC',
        slug: 'santa-cruz-stigmata-cc',
        description: 'Carbon gravel bike with dropped seatstays, SRAM Rival eTap AXS, and tire clearance up to 50mm.',
        price: 4999.99,
        category: createdCategories[6]._id,
        images: ['https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800'],
        stock: 6,
        tags: ['gravel', 'santa-cruz', 'carbon', 'premium'],
        featured: false,
        rating: 4.9,
        numReviews: 52,
      },
      {
        name: 'Salsa Journeyman Apex 1',
        slug: 'salsa-journeyman-apex-1',
        description: 'Steel gravel bike with classic geometry, SRAM Apex 1x11, and versatile touring capability.',
        price: 1899.99,
        category: createdCategories[6]._id,
        images: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800'],
        stock: 13,
        tags: ['gravel', 'salsa', 'steel', 'touring'],
        featured: false,
        rating: 4.6,
        numReviews: 94,
      },

      // CRUISER BIKES (Category 7) - 5 bikes
      {
        name: 'Electra Townie 7D',
        slug: 'electra-townie-7d',
        description: 'Comfort cruiser with Flat Foot Technology, 7-speed, and upright riding position.',
        price: 599.99,
        compareAtPrice: 649.99,
        category: createdCategories[7]._id,
        images: [
          'https://images.unsplash.com/photo-1559589689-577aabd1db4f?w=800',
          'https://images.unsplash.com/photo-1475090169767-40ed8d1ca1d8?w=800',
        ],
        stock: 22,
        tags: ['cruiser', 'electra', 'comfort', 'featured'],
        featured: true,
        rating: 4.8,
        numReviews: 245,
      },
      {
        name: 'Schwinn Huron 7',
        slug: 'schwinn-huron-7',
        description: 'Classic cruiser with steel frame, 7-speed Shimano, and retro styling.',
        price: 399.99,
        category: createdCategories[7]._id,
        images: ['https://images.unsplash.com/photo-1559589689-577aabd1db4f?w=800'],
        stock: 28,
        tags: ['cruiser', 'schwinn', 'classic', 'value'],
        featured: false,
        rating: 4.5,
        numReviews: 178,
      },
      {
        name: 'sixthreezero Around the Block',
        slug: 'sixthreezero-around-block',
        description: 'Women\'s cruiser with 7-speed, dual-spring saddle, and matching accessories.',
        price: 449.99,
        category: createdCategories[7]._id,
        images: ['https://images.unsplash.com/photo-1475090169767-40ed8d1ca1d8?w=800'],
        stock: 24,
        tags: ['cruiser', 'sixthreezero', 'womens', 'comfort'],
        featured: false,
        rating: 4.7,
        numReviews: 192,
      },
      {
        name: 'Priority Coast',
        slug: 'priority-coast',
        description: 'Modern cruiser with Gates Carbon Drive, 3-speed internal hub, and maintenance-free design.',
        price: 899.99,
        category: createdCategories[7]._id,
        images: ['https://images.unsplash.com/photo-1559589689-577aabd1db4f?w=800'],
        stock: 16,
        tags: ['cruiser', 'priority', 'belt-drive', 'low-maintenance'],
        featured: false,
        rating: 4.9,
        numReviews: 87,
      },
      {
        name: 'Firmstrong Bruiser Man',
        slug: 'firmstrong-bruiser-man',
        description: 'Beach cruiser with fat tires, single-speed, coaster brake, and laid-back geometry.',
        price: 349.99,
        category: createdCategories[7]._id,
        images: ['https://images.unsplash.com/photo-1475090169767-40ed8d1ca1d8?w=800'],
        stock: 30,
        tags: ['cruiser', 'firmstrong', 'beach', 'single-speed'],
        featured: false,
        rating: 4.4,
        numReviews: 134,
      },
    ];

    await Product.insertMany(products);
    console.log('Products created');

    console.log('Database seeded successfully!');
    console.log(`Created ${categories.length} categories and ${products.length} bikes`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDB();
